### ISSUE TITLE
FSM development

### ISSUE THREAD

**Issue by pdrapoport** [pdrapoport/ESL18#3]
Simplest FSM implementation. State should be changed on number key pressed.

Expected:
- [x] code
- [x] test results

Documentation is unnecessary.

**Comment by ruedales** [comment]
![image](https://user-images.githubusercontent.com/36366263/39530649-b19f5278-4e29-11e8-9cbf-10806805013a.png)

Basic implementation according to the diagram. 

FSM.c Reading of the incoming messages from the PC->Drone ToBeDone (Implementation of protocol required in order to read the messages)

**Comment by ruedales** [comment]
![image](https://user-images.githubusercontent.com/36366263/39535046-3a86badc-4e33-11e8-91bf-99a716239913.png)
Updated removing height = 0 condition
