### ISSUE TITLE
To implement before May 29th

### ISSUE THREAD

**Issue by VincBej** [pdrapoport/ESL18#9]
- [x] Drone go to panic mode when "Escape" and "Fire" is pressed
- [x] Drone go to panic mode when link is lost
- [x] Yaw control should be less smooth
- [x] Mode switch should only happen when motors are off

**Comment by harissuwig** [comment]
what has been done:
- Integrate joystick reading with keyboard reading
- Add the safety feature: Checking motor value before changing to any other states
- Fix FSM: Fixes some bug where the FSM doesn't work as intended

Note that I haven't tested this on the actual board, but the compiler is okay with the code, need testing for that

**Comment by VincBej** [comment]
Everything has been implemented and tested.
See #10.
